name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
        build_type: [Release]
        build_with_mutex: [ON, OFF]
        build_with_atomic: [ON, OFF]
        build_with_cout_info: [ON, OFF]
  
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
       submodules: recursive
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_WITH_MUTEX:BOOL=${{ matrix.build_with_mutex }} -DBUILD_WITH_ATOMIC:BOOL=${{ matrix.build_with_atomic }} -DBUILD_WITH_COUT_INFO:BOOL=${{ matrix.build_with_cout_info }}
        
    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type }}
